# Generated by Django 5.0.1 on 2026-02-06 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('prepago', 'Prepago'), ('postpago', 'Postpago')], max_length=10)),
                ('correo_electronico', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido', regex='^\\+?1?\\d{7,15}$')])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('tipo_empresa', models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], max_length=10)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El NIT solo puede contener números y guiones', regex='^[0-9\\-]+$')])),
                ('celular', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número de celular inválido', regex='^\\+?1?\\d{7,15}$')])),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='PersonaParticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('prepago', 'Prepago'), ('postpago', 'Postpago')], max_length=10)),
                ('correo_electronico', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido', regex='^\\+?1?\\d{7,15}$')])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('carnet_identidad', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El carnet de identidad solo puede contener letras mayúsculas, números y guiones', regex='^[A-Z0-9\\-]+$')])),
                ('celular', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número de celular inválido', regex='^\\+?1?\\d{7,15}$')])),
            ],
            options={
                'verbose_name': 'Persona Particular',
                'verbose_name_plural': 'Personas Particulares',
                'db_table': 'persona_particular',
            },
        ),
    ]
